version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sdc-products
hooks:
  BeforeInstall:
    - location: scripts/node_setup.sh
      runas: ubuntu
    - location: scripts/codedeploy_setup.sh
      runas: ubuntu