version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sdc-products
permissions:
  - object: /home/ubuntu/sdc-api
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file
  - object: /home/ubuntu/sdc-api/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/node_setup.sh
      runas: ubuntu
    - location: scripts/codedeploy_setup.sh
      runas: ubuntu